SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;

create table CDW_SAPP_D_BRANCH
(BRANCH_CODE int, 
 BRANCH_NAME string,
 BRANCH_STREET string,
 BRANCH_CITY string,
 BRANCH_ZIP int,
 BRANCH_PHONE string,
 LAST_UPDATED timestamp)
partitioned by (BRANCH_STATE string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' 
ESCAPED BY '"' LINES TERMINATED BY '\n'
stored as textfile
location "/user/maria_dev/CREDIT_CARD_OOZIE_DYNAMIC/CDW_SAPP_D_BRANCH";
